name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Instalação do fortune
      id: instalacao-do-fortune
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Instalação do fortune
        setup-command: "./.tests/fortune.sh"
        command: "./trabalho.sh"
        timeout: 10
        max-score: 1
    - name: Execução do fortune 3 vezes
      id: execucao-do-fortune-3-vezes
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Execução do fortune 3 vezes
        setup-command: "./trabalho.sh"
        command: "./.tests/arquivos_criados.sh"
        timeout: 10
        max-score: 1
    - name: Concatenação dos arquivos
      id: concatenacao-dos-arquivos
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Concatenação dos arquivos
        setup-command: "./trabalho.sh"
        command: "./.tests/concatenacao.sh"
        timeout: 10
        max-score: 1
    - name: Anexação a arquivo
      id: anexacao-a-arquivo
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Anexação a arquivo
        setup-command: "./trabalho.sh"
        command: "./.tests/anexo.sh"
        timeout: 10
        max-score: 1
    - name: Contagem de linhas em arquivo
      id: contagem-de-linhas-em-arquivo
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Contagem de linhas em arquivo
        setup-command: "./trabalho.sh"
        command: "./.tests/quantidade_linhas.sh"
        timeout: 10
        max-score: 1
    - name: Contagem de letras em um arquivo
      id: contagem-de-letras-em-um-arquivo
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Contagem de letras em um arquivo
        setup-command: "./trabalho.sh"
        command: "./.tests/quantidade_letras.sh"
        timeout: 10
        max-score: 1
    - name: Saída normal e de erros separados em arquivos
      id: saida-normal-e-de-erros-separados-em-arquivos
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Saída normal e de erros separados em arquivos
        setup-command: "./trabalho.sh"
        command: "./.tests/conteudo_etc.sh"
        timeout: 10
        max-score: 1
    - name: Saída normal e de erros salvos em um único arquivo
      id: saida-normal-e-de-erros-salvos-em-um-unico-arquivo
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Saída normal e de erros salvos em um único arquivo
        setup-command: "./trabalho.sh"
        command: "./.tests/saida_com_erros.sh"
        timeout: 10
        max-score: 1
    - name: Nomes dos usuários do sistema
      id: nomes-dos-usuarios-do-sistema
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Nomes dos usuários do sistema
        setup-command: "./trabalho.sh"
        command: "./.tests/usuarios.sh"
        timeout: 10
        max-score: 1
    - name: Usuários do sistema ordenados em ordem alfabética
      id: usuarios-do-sistema-ordenados-em-ordem-alfabetica
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Usuários do sistema ordenados em ordem alfabética
        setup-command: "./trabalho.sh"
        command: "./.tests/usuarios_ordenados.sh"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INSTALACAO-DO-FORTUNE_RESULTS: "${{steps.instalacao-do-fortune.outputs.result}}"
        EXECUCAO-DO-FORTUNE-3-VEZES_RESULTS: "${{steps.execucao-do-fortune-3-vezes.outputs.result}}"
        CONCATENACAO-DOS-ARQUIVOS_RESULTS: "${{steps.concatenacao-dos-arquivos.outputs.result}}"
        ANEXACAO-A-ARQUIVO_RESULTS: "${{steps.anexacao-a-arquivo.outputs.result}}"
        CONTAGEM-DE-LINHAS-EM-ARQUIVO_RESULTS: "${{steps.contagem-de-linhas-em-arquivo.outputs.result}}"
        CONTAGEM-DE-LETRAS-EM-UM-ARQUIVO_RESULTS: "${{steps.contagem-de-letras-em-um-arquivo.outputs.result}}"
        SAIDA-NORMAL-E-DE-ERROS-SEPARADOS-EM-ARQUIVOS_RESULTS: "${{steps.saida-normal-e-de-erros-separados-em-arquivos.outputs.result}}"
        SAIDA-NORMAL-E-DE-ERROS-SALVOS-EM-UM-UNICO-ARQUIVO_RESULTS: "${{steps.saida-normal-e-de-erros-salvos-em-um-unico-arquivo.outputs.result}}"
        NOMES-DOS-USUARIOS-DO-SISTEMA_RESULTS: "${{steps.nomes-dos-usuarios-do-sistema.outputs.result}}"
        USUARIOS-DO-SISTEMA-ORDENADOS-EM-ORDEM-ALFABETICA_RESULTS: "${{steps.usuarios-do-sistema-ordenados-em-ordem-alfabetica.outputs.result}}"
      with:
        runners: instalacao-do-fortune,execucao-do-fortune-3-vezes,concatenacao-dos-arquivos,anexacao-a-arquivo,contagem-de-linhas-em-arquivo,contagem-de-letras-em-um-arquivo,saida-normal-e-de-erros-separados-em-arquivos,saida-normal-e-de-erros-salvos-em-um-unico-arquivo,nomes-dos-usuarios-do-sistema,usuarios-do-sistema-ordenados-em-ordem-alfabetica
